# Generated by Django 4.0.2 on 2022-02-15 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileproc', '0002_auto_20220215_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records_country', to='fileproc.country'),
        ),
        migrations.AlterField(
            model_name='records',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records_currency', to='fileproc.country'),
        ),
    ]
