# Generated by Django 4.0.2 on 2022-02-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileproc', '0003_alter_records_country_alter_records_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerateholder',
            name='rate',
            field=models.DecimalField(decimal_places=16, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
